### ISSUE TITLE
upload field not saving

### ISSUE THREAD

**Issue by mi32dogs** [wernerkrauss/hasoneedit#1]
Hi, it works fine with regular fields but I have a upload field in my has_one this one is not saving.

Any idea how to fix this?

**Comment by wernerkrauss** [comment]
Hi @mi32dogs, this is just a private repo i made after the original source was abandoned. The somehow "official" fork afaik is https://github.com/stevie-mayhew/hasoneedit where you already posted this issue (see https://github.com/stevie-mayhew/hasoneedit/issues/4 ). And sorry, i don't have an idea. I guess that's a hard one, cause upload field relies to be a relation of the current DataObject and hasoneedit masks that relation in the object name.

A workaround would be to put the relation to the original Dataobject and only textfields in the has_one relation.
